import { useState, useCallback, useEffect } from 'react';
import { motion } from 'framer-motion';
import { jsPDF } from 'jspdf';
import {
  VOWELS, CONSONANT_GROUPS, NUMERALS, ALL_CONSONANTS,
} from '../data/takri-mappings';
import { showToast } from '../lib/script-utils';
import { consumePracticeSheetsImport } from '../lib/tool-bridge';
import './PracticeSheets.css';

// ============================================================
// Character group definitions for the UI
// ============================================================

const CHAR_GROUPS = [
  { id: 'vowels', label: 'Vowels (स्वर)', chars: VOWELS },
  ...CONSONANT_GROUPS.map(g => ({
    id: g.nameShort,
    label: g.name,
    chars: g.consonants,
  })),
  { id: 'numerals', label: 'Numerals (अंक)', chars: NUMERALS.map(n => ({
    takri: n.takri, devanagari: n.devanagari, roman: String(n.value), name: `Digit ${n.value}`,
  })) },
];

const DISPLAY_MODES = [
  { id: 'takri-dev-roman', label: 'Takri + Devanagari + Roman' },
  { id: 'takri-dev', label: 'Takri + Devanagari' },
  { id: 'takri-only', label: 'Takri Only' },
];

const PAPER_SIZES = [
  { id: 'a4', label: 'A4', width: 210, height: 297 },
  { id: 'letter', label: 'Letter', width: 215.9, height: 279.4 },
];

// ============================================================
// PDF Generation — renders Takri text to canvas then to PDF
// ============================================================

function renderTextToImage(text, fontFamily, fontSize, color = '#000000') {
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');
  const dpr = 3; // high-res
  ctx.font = `${fontSize * dpr}px ${fontFamily}`;
  const metrics = ctx.measureText(text);
  const width = Math.ceil(metrics.width) + 4;
  const height = Math.ceil(fontSize * dpr * 1.5);
  canvas.width = width;
  canvas.height = height;
  ctx.font = `${fontSize * dpr}px ${fontFamily}`;
  ctx.fillStyle = color;
  ctx.textBaseline = 'middle';
  ctx.fillText(text, 0, height * 0.55);
  return { dataUrl: canvas.toDataURL('image/png'), width, height };
}

function addTextImage(doc, text, fontFamily, fontSize, x, y, cellH, color = '#000000') {
  const { dataUrl, width, height } = renderTextToImage(text, fontFamily, fontSize, color);
  const scale = (cellH * 0.7) / height;
  const imgW = width * scale;
  const imgH = height * scale;
  doc.addImage(dataUrl, 'PNG', x, y + (cellH - imgH) / 2, imgW, imgH);
  return imgW;
}

async function generatePDF({ selectedGroups, reps, displayMode, paperSize }) {
  const paper = PAPER_SIZES.find(p => p.id === paperSize) || PAPER_SIZES[0];
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: [paper.width, paper.height] });

  const margin = 15;
  const pageW = paper.width - margin * 2;
  let curY = margin;

  // Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Takri Alphabet Writing Practice', paper.width / 2, curY + 6, { align: 'center' });
  curY += 14;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text('Takri Script (Unicode U+11680) | Generated by Takri Tools', paper.width / 2, curY, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  curY += 10;

  // Gather chars
  const chars = [];
  for (const group of CHAR_GROUPS) {
    if (selectedGroups.includes(group.id)) {
      chars.push(...group.chars.map(c => ({ ...c, groupLabel: group.label })));
    }
  }

  if (chars.length === 0) return null;

  const rowH = 10; // height of each row in mm
  const headerH = 12;
  let lastGroup = '';

  for (const char of chars) {
    // Check page break
    const neededH = (char.groupLabel !== lastGroup ? headerH : 0) + rowH * (1 + reps);
    if (curY + neededH > paper.height - margin) {
      doc.addPage();
      curY = margin;
    }

    // Group header
    if (char.groupLabel !== lastGroup) {
      lastGroup = char.groupLabel;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(180, 120, 0);
      doc.text(char.groupLabel, margin, curY + 6);
      doc.setTextColor(0, 0, 0);
      curY += headerH;
    }

    // Character header row — Takri char (large) | Devanagari | Roman
    const cellW = 14;
    const charRowY = curY;

    // Draw background for the header
    doc.setFillColor(250, 245, 230);
    doc.rect(margin, charRowY, pageW, rowH, 'F');

    // Draw left border accent
    doc.setFillColor(240, 165, 0);
    doc.rect(margin, charRowY, 1.5, rowH, 'F');

    // Takri character (large, rendered as image)
    let xPos = margin + 4;
    const takImgW = addTextImage(doc, char.takri, "'Noto Sans Takri', sans-serif", 14, xPos, charRowY, rowH, '#4a2c82');
    xPos += Math.max(takImgW, cellW);

    // Devanagari equivalent
    if (displayMode !== 'takri-only') {
      const devImgW = addTextImage(doc, char.devanagari, "'Noto Sans Devanagari', sans-serif", 12, xPos, charRowY, rowH, '#1a6cb0');
      xPos += Math.max(devImgW, cellW);
    }

    // Roman transliteration
    if (displayMode === 'takri-dev-roman') {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(char.roman || '', xPos, charRowY + rowH * 0.6);
      doc.setTextColor(0, 0, 0);
      xPos += cellW;
    }

    // Practice cells — light gray guide characters
    const practiceStartX = Math.max(xPos + 2, margin + 50);
    const practiceCellW = (margin + pageW - practiceStartX) / 8; // 8 practice cells

    for (let c = 0; c < 8 && practiceStartX + c * practiceCellW < margin + pageW; c++) {
      const cx = practiceStartX + c * practiceCellW;
      // Dotted cell border
      doc.setDrawColor(200, 200, 200);
      doc.setLineDashPattern([0.5, 0.5], 0);
      doc.rect(cx, charRowY, practiceCellW, rowH);

      // Light gray guide character
      if (c < 2) {
        addTextImage(doc, char.takri, "'Noto Sans Takri', sans-serif", 12, cx + 1, charRowY, rowH, '#d0d0d0');
      }
    }

    doc.setLineDashPattern([], 0);
    curY += rowH;

    // Empty practice rows
    for (let r = 0; r < reps; r++) {
      if (curY + rowH > paper.height - margin) {
        doc.addPage();
        curY = margin;
      }

      // Ruled lines
      doc.setDrawColor(220, 220, 220);
      doc.line(margin, curY, margin + pageW, curY); // top
      doc.setDrawColor(235, 235, 235);
      doc.setLineDashPattern([0.5, 1], 0);
      doc.line(margin, curY + rowH / 2, margin + pageW, curY + rowH / 2); // middle dashed
      doc.setLineDashPattern([], 0);
      doc.setDrawColor(220, 220, 220);
      doc.line(margin, curY + rowH, margin + pageW, curY + rowH); // bottom

      curY += rowH;
    }

    curY += 3; // spacing between characters
  }

  // Footer on last page
  doc.setFontSize(7);
  doc.setTextColor(160, 160, 160);
  doc.text('Generated by Takri Tools — takri-tools', paper.width / 2, paper.height - 8, { align: 'center' });

  return doc;
}

// ============================================================
// React Component
// ============================================================

const fadeIn = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

export default function PracticeSheets() {
  const [selectedGroups, setSelectedGroups] = useState(['vowels']);
  const [reps, setReps] = useState(2);
  const [displayMode, setDisplayMode] = useState('takri-dev-roman');
  const [paperSize, setPaperSize] = useState('a4');
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    const imported = consumePracticeSheetsImport();
    if (!imported?.groupIds?.length) return;
    setSelectedGroups(imported.groupIds);
    showToast(
      imported.title
        ? `Loaded practice groups for: ${imported.title}`
        : 'Character groups loaded from Reader',
    );
  }, []);

  const toggleGroup = useCallback((id) => {
    setSelectedGroups(prev =>
      prev.includes(id) ? prev.filter(g => g !== id) : [...prev, id]
    );
  }, []);

  const selectAll = () => setSelectedGroups(CHAR_GROUPS.map(g => g.id));
  const selectNone = () => setSelectedGroups([]);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      // Small delay to let fonts render
      await new Promise(r => setTimeout(r, 100));
      const doc = await generatePDF({ selectedGroups, reps, displayMode, paperSize });
      if (doc) {
        doc.save('takri-practice-sheet.pdf');
      }
    } catch (e) {
      console.error('PDF generation error:', e);
    } finally {
      setGenerating(false);
    }
  };

  // Preview data
  const previewChars = CHAR_GROUPS
    .filter(g => selectedGroups.includes(g.id))
    .flatMap(g => g.chars.slice(0, 3));

  return (
    <motion.div
      className="practice-page"
      initial="hidden"
      animate="visible"
      variants={fadeIn}
    >
      <div className="practice-container">
        {/* Header */}
        <header className="practice-header">
          <h1>📝 Takri Practice Sheets</h1>
          <p>Generate printable PDFs for learning Takri alphabet with Devanagari associations</p>
        </header>

        <div className="practice-layout">
          {/* Configuration Panel */}
          <div className="config-panel">
            <h2 className="config-title">Configure Your Sheet</h2>

            {/* Character Groups */}
            <div className="config-section">
              <div className="config-section-header">
                <h3>Character Groups</h3>
                <div className="config-section-actions">
                  <button className="text-btn" onClick={selectAll}>All</button>
                  <button className="text-btn" onClick={selectNone}>None</button>
                </div>
              </div>
              <div className="checkbox-grid">
                {CHAR_GROUPS.map(group => (
                  <label key={group.id} className={`checkbox-item ${selectedGroups.includes(group.id) ? 'checked' : ''}`}>
                    <input
                      type="checkbox"
                      checked={selectedGroups.includes(group.id)}
                      onChange={() => toggleGroup(group.id)}
                    />
                    <span className="checkbox-label">{group.label}</span>
                    <span className="checkbox-count">{group.chars.length}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Repetitions */}
            <div className="config-section">
              <h3>Practice Rows per Character</h3>
              <div className="slider-row">
                <input
                  type="range"
                  min="1"
                  max="5"
                  value={reps}
                  onChange={(e) => setReps(Number(e.target.value))}
                  className="slider"
                />
                <span className="slider-value">{reps}</span>
              </div>
            </div>

            {/* Display Mode */}
            <div className="config-section">
              <h3>Display Mode</h3>
              <div className="radio-group">
                {DISPLAY_MODES.map(m => (
                  <label key={m.id} className={`radio-item ${displayMode === m.id ? 'active' : ''}`}>
                    <input
                      type="radio"
                      name="displayMode"
                      value={m.id}
                      checked={displayMode === m.id}
                      onChange={() => setDisplayMode(m.id)}
                    />
                    <span>{m.label}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Paper Size */}
            <div className="config-section">
              <h3>Paper Size</h3>
              <div className="radio-group radio-group--inline">
                {PAPER_SIZES.map(p => (
                  <label key={p.id} className={`radio-item ${paperSize === p.id ? 'active' : ''}`}>
                    <input
                      type="radio"
                      name="paperSize"
                      value={p.id}
                      checked={paperSize === p.id}
                      onChange={() => setPaperSize(p.id)}
                    />
                    <span>{p.label}</span>
                  </label>
                ))}
              </div>
            </div>

            {/* Generate Button */}
            <button
              className="generate-btn"
              onClick={handleGenerate}
              disabled={generating || selectedGroups.length === 0}
            >
              {generating ? (
                <>
                  <span className="spinner" />
                  Generating…
                </>
              ) : (
                <>📄 Download PDF</>
              )}
            </button>

            {selectedGroups.length === 0 && (
              <p className="config-warning">Select at least one character group</p>
            )}
          </div>

          {/* Preview Panel */}
          <div className="preview-panel">
            <h2 className="preview-title">Preview</h2>
            <div className="preview-sheet">
              <div className="preview-sheet-header">
                <span className="preview-sheet-title">Takri Alphabet Writing Practice</span>
                <span className="preview-sheet-subtitle">
                  {selectedGroups.length} group{selectedGroups.length !== 1 ? 's' : ''} · {
                    CHAR_GROUPS.filter(g => selectedGroups.includes(g.id)).reduce((s, g) => s + g.chars.length, 0)
                  } characters · {reps} practice row{reps !== 1 ? 's' : ''} each
                </span>
              </div>

              {previewChars.length === 0 ? (
                <div className="preview-empty">
                  <p>Select character groups to see a preview</p>
                </div>
              ) : (
                <div className="preview-rows">
                  {previewChars.map((char, i) => (
                    <div key={i} className="preview-row">
                      <div className="preview-char-header">
                        <span className="preview-takri">{char.takri}</span>
                        {displayMode !== 'takri-only' && (
                          <span className="preview-dev">{char.devanagari}</span>
                        )}
                        {displayMode === 'takri-dev-roman' && (
                          <span className="preview-roman">{char.roman}</span>
                        )}
                      </div>
                      <div className="preview-practice">
                        {[...Array(6)].map((_, j) => (
                          <div key={j} className="preview-practice-cell">
                            {j < 2 && (
                              <span className="preview-guide-char">{char.takri}</span>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                  {previewChars.length < CHAR_GROUPS.filter(g => selectedGroups.includes(g.id)).reduce((s, g) => s + g.chars.length, 0) && (
                    <div className="preview-more">
                      … and {CHAR_GROUPS.filter(g => selectedGroups.includes(g.id)).reduce((s, g) => s + g.chars.length, 0) - previewChars.length} more characters
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
